# Site settings
title: My Blog                # 修改：你可以改成你的博客标题
SEOTitle: 我的博客 | Webtest1   # 修改：网页标签栏显示的标题
header-img: img/post-bg-desk.jpg
email: your-email@gmail.com   # 修改：改成你的邮箱
description: "这里写你的博客简介..."
keyword: "Blog, 技术, 生活"
url: "https://llsky9.github.io"          # 【关键修改】你的 GitHub Pages 基础域名
baseurl: "/webtest1"      # 【关键修改】你的仓库名称！前面要加斜杠，解决样式丢失的核心配置！
github_repo: "https://github.com/llsky9/webtest1.git" # 【修改】你的仓库 Git 地址

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "写一句你的座右铭"
sidebar-avatar: /img/about-BY-gentle.jpg      # 头像图片，后续你可以把自己的照片放入 img 文件夹替换它



# SNS settings
RSS: false
# weibo_username:     your_id
# zhihu_username:     your_id
github_username:    llsky9    # 【修改】改成你的 GitHub 用户名，否则点头像会跳到别人那去
# facebook_username:  your_id
# jianshu_username:   your_id
# twitter_username:   your_id




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: false    # 【修改】暂时关闭，原作者的Key你用不了。等网站正常后，去申请自己的ClientID再开启
  clientID:      # 留空
  clientSecret:  # 留空
  repo: webtest1        # 你的仓库名
  owner: llsky9         # 你的用户名
  admin: llsky9
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id:  # 【修改】已清空，避免统计到原作者那里

# Google Analytics
ga_track_id:  # 【修改】已清空
ga_domain: auto               





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "我的GitHub",
        href: "https://github.com/llsky9"
    }
]
